name: Build and deploy ASP.Net Core app to Azure Web App - azureweb

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  PROJECT_PATH: '.' 
  # Using a standard path for the build output
  OUTPUT_PATH: './publish'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: dotnet restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build with dotnet
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: dotnet publish
        # We publish to a specific folder
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.OUTPUT_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: net-app-artifact
          # Upload the contents of the publish folder
          path: ${{ env.OUTPUT_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      # Download into the current working directory
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app-artifact
          path: .
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'azureweb'
          slot-name: 'Production'
          # Use '.' so that the files in the current directory are zipped directly
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7C4B86217AFE49EA884D93037534B88B }}
